tinyMCE.addI18n('en.exmsystem',{
    exm_more_desc : 'Insert "more" Tag',
    exm_page_desc : 'Insert "Next Page" Tag',
    exm_adv_desc : 'Advanced Toolbar',
    exm_img_desc : 'Show EXM Image Manager',
    exm_img_dlgtitle : 'Administrador de imágenes',
    exm_icons_desc : 'Insert Emoticons',
    exm_more_alt : 'More...',
    exm_page_alt : 'Next Page...',
    // Administrador de IMágenes
    tab_name : 'Administrador de Imágenes',
tab_props: 'Propiedades de Imágen',
select_catego: 'Categoría:',
select_option: 'Seleccionar...',
insert_thumb_tip: 'Insertar Miniatura de la Imágen',
insert_img_tip: 'Insertar Imágen Normal',
insert_link_tip: 'Insertar Imágenes Enlazadas',
show_results: 'Resultados:',
last_page: 'Última Página',
next_page: 'Página Siguiente',
first_page: 'Primer Página',
prev_page: 'Página Anterior',
image_title: 'Titulo',
image_desc: 'Descripción',
image_width: 'Ancho',
image_height: 'Alto',
class_name: 'Clase',
custom_class: 'Otra Clase',
cols_number: 'Columnas:',
change: 'Cambiar',
sel_image: 'Imágen',
css_style: 'Estilos CSS',
img_align: 'Alineación',
no_selected: 'Selecciona una imágen primero.',
no_title: 'Sin Título',
tab_upload: 'Cargar Imágen',
form_file: 'Archivo de Imágen',
form_catego: 'Categoría',
form_title: 'Título de la Imágen',
form_desc: 'Descripción de la Imágen',
form_button: 'Cargar Ahora',
validate_email: 'debe contener una dirección de correo electrónico.',
validate_option: 'la opción seleccionada no es válida.',
validate_req: 'es requerido.',
validate_errors: 'Ocurrieron los siguientes errores.',
image_border: 'Borde',
xi_vspace: 'Espacio Vertical',
xi_hspace: 'Espacio Horizontal',
xi_target: 'Target',
xi_showas: 'Mostrar Como',
xi_showaspage: 'Página',
xi_showasimg: 'Imágen',
insert: 'Insertar',
cancel: 'Cancelar',
not_set: 'Ninguna'
});